export default {
	nearby: require('src/assets/images/map.png'),
	list: require('src/assets/images/list.png'),
	location_icon: require('src/assets/images/location_icon.png'),
	no_location: require('src/assets/images/no_location_illustration.png'),
	verified: require('src/assets/images/verified.png'),
	pin_location: require('src/assets/images/pin_location.png'),
	close: require('src/assets/images/close.png'),
	heart_empty: require('src/assets/images/heart_empty.png'),
	bed: require('src/assets/images/bed.png'),
	bath: require('src/assets/images/bath.png'),
	condo: require('src/assets/images/condo.png'),
	garage: require('src/assets/images/garage.png'),
	area: require('src/assets/images/area.png'),
	default_image: require('src/assets/images/default_image.png'),
	menu: require('src/assets/images/menu.png'),
}